version: '3.8'

services:
  product-canvas:
    image: 935732994/pmtools
    ports:
      - "3000:3000"
    container_name: product-canvas-app
    restart: unless-stopped
    environment:
      # 是否启用图片解析功能（Vision API），默认启用
      - ENABLE_VISION=true
    #volumes:
      # 可选：挂载自定义配置文件覆盖默认配置
      # - ./config.json:/usr/share/nginx/html/config.json:ro